"""
Author: Lorenzo Baldazzi
Date: 2026-06-08

Neural network training for stability prediction.

Goal: Train a neural network on the stability samples generated by
tpm_stability_map.py and save the model and scaler for later use.

Usage
-----
    # Train with default parameters
    python Stability_nn.py --data stability_map.pkl --outdir ./models
    
    # With custom training parameters
    python Stability_nn.py --data stability_map.pkl --outdir ./models --epochs 2000 --lr 0.0001
    
    # Using specific GPU device
    python Stability_nn.py --data stability_map.pkl --outdir ./models --device cuda:0
"""

import argparse
import os
import pickle
import sys

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# ----------------------------------------------------------------------
# 1. NEURAL NETWORK ARCHITECTURE
# ----------------------------------------------------------------------

class StabilityOracle(nn.Module):
    """Multi-layer perceptron for stability prediction."""
    
    def __init__(self, input_dim: int, hidden_dims: list = None):
        """
        Initialize the network.
        
        Parameters
        ----------
        input_dim : int
            Dimension of input features (number of parameters)
        hidden_dims : list, optional
            Dimensions of hidden layers. Default: [64, 64, 32]
        """
        super(StabilityOracle, self).__init__()
        
        if hidden_dims is None:
            hidden_dims = [64, 64, 32]
        
        # Build network dynamically
        layers = []
        prev_dim = input_dim
        
        for hidden_dim in hidden_dims:
            layers.append(nn.Linear(prev_dim, hidden_dim))
            layers.append(nn.ReLU())
            prev_dim = hidden_dim
        
        # Output layer (single value: log-odds of stability)
        layers.append(nn.Linear(prev_dim, 1))
        
        self.network = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass through the network."""
        return self.network(x)


# ----------------------------------------------------------------------
# 2. TRAINING UTILITIES
# ----------------------------------------------------------------------

def validate_data(data: dict) -> None:
    """Validate that the data pickle contains required keys."""
    required_keys = ["points", "stable", "param_names"]
    for key in required_keys:
        if key not in data:
            raise ValueError(f"Data pickle missing required key: {key}")
    
    if len(data["points"]) != len(data["stable"]):
        raise ValueError("Mismatch between points and stable labels")


def train_epoch(model: nn.Module,
                train_loader: torch.utils.data.DataLoader,
                criterion: nn.Module,
                optimizer: torch.optim.Optimizer,
                device: torch.device) -> float:
    """Train for one epoch and return average loss."""
    model.train()
    total_loss = 0.0
    
    for X_batch, y_batch in train_loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)
        
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item() * len(X_batch)
    
    return total_loss / len(train_loader.dataset)


def validate(model: nn.Module,
             val_loader: torch.utils.data.DataLoader,
             criterion: nn.Module,
             device: torch.device) -> tuple:
    """Validate the model and return loss and accuracy."""
    model.eval()
    total_loss = 0.0
    total_correct = 0
    total_samples = 0
    
    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            total_loss += loss.item() * len(X_batch)
            
            # Calculate accuracy
            predictions = (torch.sigmoid(outputs) >= 0.5).float()
            total_correct += (predictions == y_batch).sum().item()
            total_samples += len(X_batch)
    
    avg_loss = total_loss / total_samples
    accuracy = total_correct / total_samples
    
    return avg_loss, accuracy


# ----------------------------------------------------------------------
# 3. MAIN TRAINING FUNCTION
# ----------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--data", required=True,
                    help="Path to the pickle file generated by tpm_stability_map.py")
    ap.add_argument("--outdir", default=".",
                    help="Output directory for model and scaler (default: %(default)s)")
    ap.add_argument("--model-name", default="stability_model.pt",
                    help="Name of the model file (default: %(default)s)")
    ap.add_argument("--scaler-name", default="stability_scaler.pkl",
                    help="Name of the scaler file (default: %(default)s)")
    ap.add_argument("--epochs", type=int, default=1000,
                    help="Number of training epochs (default: %(default)s)")
    ap.add_argument("--batch-size", type=int, default=32,
                    help="Batch size for training (default: %(default)s)")
    ap.add_argument("--lr", type=float, default=0.001,
                    help="Learning rate (default: %(default)s)")
    ap.add_argument("--val-split", type=float, default=0.2,
                    help="Validation split fraction (default: %(default)s)")
    ap.add_argument("--hidden-dims", type=int, nargs="+", default=[64, 64, 32],
                    help="Hidden layer dimensions (default: %(default)s)")
    ap.add_argument("--device", default=None,
                    help="Device to use (cuda, cpu, mps, cuda:0, etc). Auto-detect if not specified.")
    ap.add_argument("--seed", type=int, default=42,
                    help="Random seed for reproducibility (default: %(default)s)")
    ap.add_argument("--early-stopping", type=int, default=50,
                    help="Early stopping patience (epochs without improvement). "
                         "Set to -1 to disable (default: %(default)s)")
    
    args = ap.parse_args()

    # Set random seeds for reproducibility
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    # Determine device
    if args.device:
        device = torch.device(args.device)
        if "cuda" in str(device):
            print(f"Using CUDA device: {device}")
        elif "mps" in str(device):
            print("Using Apple Metal Performance Shaders (MPS)")
        else:
            print(f"Using {device}")
    else:
        # Auto-detect
        if torch.cuda.is_available():
            device = torch.device("cuda")
            print(f"Using CUDA device (auto-detected)")
        elif torch.backends.mps.is_available():
            device = torch.device("mps")
            print("Using Apple Metal Performance Shaders (MPS, auto-detected)")
        else:
            device = torch.device("cpu")
            print("Using CPU (auto-detected)")

    # Create output directory
    os.makedirs(args.outdir, exist_ok=True)

    print("=" * 64)
    print(" Neural Network Training for Stability Prediction")
    print("=" * 64)
    print(f"   Data file       : {args.data}")
    print(f"   Output dir      : {args.outdir}")
    print(f"   Device          : {device}")
    print(f"   Epochs          : {args.epochs}")
    print(f"   Batch size      : {args.batch_size}")
    print(f"   Learning rate   : {args.lr}")
    print(f"   Hidden dims     : {args.hidden_dims}")
    print(f"   Early stopping  : {args.early_stopping if args.early_stopping > 0 else 'disabled'}")
    print()

    # ---- A. Loading Data ----
    print("[1/5] Loading data ...")
    if not os.path.exists(args.data):
        print(f"ERROR: Data file not found: {args.data}", file=sys.stderr)
        sys.exit(1)

    try:
        with open(args.data, "rb") as f:
            data = pickle.load(f)
        validate_data(data)
    except (ValueError, KeyError) as e:
        print(f"ERROR: Invalid data file: {e}", file=sys.stderr)
        sys.exit(1)

    X = data["points"].astype(np.float32)
    y = data["stable"].astype(np.float32)
    param_names = data["param_names"]

    print(f"      Loaded {len(X)} samples")
    print(f"      Parameters: {param_names}")
    print(f"      Stable fraction: {y.mean():.3f}")
    print(f"      Input dimension: {X.shape[1]}")
    print()

    # ---- B. Preprocessing ----
    print("[2/5] Data preprocessing and splitting ...")
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=args.val_split, random_state=args.seed
    )

    # Standardize data (crucial for neural networks)
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train).astype(np.float32)
    X_val_scaled = scaler.transform(X_val).astype(np.float32)

    # Convert to PyTorch tensors
    X_train_t = torch.tensor(X_train_scaled, dtype=torch.float32)
    y_train_t = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
    X_val_t = torch.tensor(X_val_scaled, dtype=torch.float32)
    y_val_t = torch.tensor(y_val, dtype=torch.float32).view(-1, 1)

    # Create data loaders
    train_dataset = torch.utils.data.TensorDataset(X_train_t, y_train_t)
    val_dataset = torch.utils.data.TensorDataset(X_val_t, y_val_t)

    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=args.batch_size, shuffle=True
    )
    val_loader = torch.utils.data.DataLoader(
        val_dataset, batch_size=args.batch_size, shuffle=False
    )

    print(f"      Training samples: {len(X_train)}")
    print(f"      Validation samples: {len(X_val)}")
    print()

    # ---- C. Model Initialization ----
    print("[3/5] Model initialization ...")
    model = StabilityOracle(input_dim=X.shape[1], hidden_dims=args.hidden_dims)
    model = model.to(device)

    criterion = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=args.lr)

    print(f"      Model structure:")
    total_params = 0
    for name, param in model.named_parameters():
        n_params = param.numel()
        total_params += n_params
        print(f"         {name}: {param.shape} ({n_params:,} parameters)")
    print(f"      Total parameters: {total_params:,}")
    print()

    # ---- D. Training Loop ----
    print("[4/5] Training ...")
    best_val_loss = float('inf')
    best_model_path = os.path.join(args.outdir, args.model_name)
    patience = args.early_stopping if args.early_stopping > 0 else float('inf')
    patience_counter = 0

    for epoch in range(args.epochs):
        train_loss = train_epoch(model, train_loader, criterion, optimizer, device)

        # Validation every 50 epochs
        if (epoch + 1) % 50 == 0:
            val_loss, val_acc = validate(model, val_loader, criterion, device)

            print(f"      Epoch [{epoch+1:4d}/{args.epochs}] "
                  f"| Train Loss: {train_loss:.4f} "
                  f"| Val Loss: {val_loss:.4f} "
                  f"| Val Acc: {val_acc*100:.2f}%")

            # Save the best model and implement early stopping
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                patience_counter = 0
                torch.save(model.state_dict(), best_model_path)
            else:
                patience_counter += 1

            # Early stopping
            if patience_counter >= patience:
                print(f"      Early stopping triggered: no improvement for {patience} validation checks")
                break

    print()

    # ---- E. Load Best Model and Final Evaluation ----
    print("[5/5] Final evaluation and saving ...")
    model.load_state_dict(torch.load(best_model_path, map_location=device))
    final_val_loss, final_val_acc = validate(model, val_loader, criterion, device)

    print(f"      Final validation loss: {final_val_loss:.4f}")
    print(f"      Final validation accuracy: {final_val_acc*100:.2f}%")
    print()

    # Save scaler
    scaler_path = os.path.join(args.outdir, args.scaler_name)
    with open(scaler_path, "wb") as f:
        pickle.dump(scaler, f)

    print("Generated artifacts:")
    print(f"  ✓ {best_model_path}")
    print(f"    Neural network weights (best validation model)")
    print(f"  ✓ {scaler_path}")
    print(f"    Parameter normalization scaler")
    print()
    print("Usage in inference:")
    print("  import torch, pickle")
    print("  from Stability_nn import StabilityOracle")
    print()
    print("  # Load artifacts")
    print("  scaler = pickle.load(open(scaler_file, 'rb'))")
    print("  model = StabilityOracle(input_dim=4)  # or read from checkpoint")
    print("  model.load_state_dict(torch.load(model_file))")
    print("  model.eval()")
    print()
    print("  # Predict on new data")
    print("  x_new = ...  # raw parameters")
    print("  x_scaled = scaler.transform(x_new)")
    print("  with torch.no_grad():")
    print("      output = model(torch.tensor(x_scaled, dtype=torch.float32))")
    print("      prob = torch.sigmoid(output)")


if __name__ == "__main__":
    sys.exit(main())
